/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as LogInIndexRouteImport } from './routes/log-in/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedLedgerRouteImport } from './routes/_authenticated/ledger'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/_admin'
import { Route as AuthenticatedTimelineIndexRouteImport } from './routes/_authenticated/timeline/index'
import { Route as AuthenticatedRoomsIndexRouteImport } from './routes/_authenticated/rooms/index'
import { Route as AuthenticatedBookingsIndexRouteImport } from './routes/_authenticated/bookings/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AuthenticatedBookingsBookingIdRouteImport } from './routes/_authenticated/bookings/$bookingId'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/_admin/users'
import { Route as AuthenticatedRoomsRoomIdIndexRouteImport } from './routes/_authenticated/rooms/$roomId/index'
import { Route as AuthenticatedRoomsRoomIdHistoryRouteImport } from './routes/_authenticated/rooms/$roomId/history'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LogInIndexRoute = LogInIndexRouteImport.update({
  id: '/log-in/',
  path: '/log-in/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLedgerRoute = AuthenticatedLedgerRouteImport.update({
  id: '/ledger',
  path: '/ledger',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTimelineIndexRoute =
  AuthenticatedTimelineIndexRouteImport.update({
    id: '/timeline/',
    path: '/timeline/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRoomsIndexRoute = AuthenticatedRoomsIndexRouteImport.update({
  id: '/rooms/',
  path: '/rooms/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBookingsIndexRoute =
  AuthenticatedBookingsIndexRouteImport.update({
    id: '/bookings/',
    path: '/bookings/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedBookingsBookingIdRoute =
  AuthenticatedBookingsBookingIdRouteImport.update({
    id: '/bookings/$bookingId',
    path: '/bookings/$bookingId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedRoomsRoomIdIndexRoute =
  AuthenticatedRoomsRoomIdIndexRouteImport.update({
    id: '/rooms/$roomId/',
    path: '/rooms/$roomId/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRoomsRoomIdHistoryRoute =
  AuthenticatedRoomsRoomIdHistoryRouteImport.update({
    id: '/rooms/$roomId/history',
    path: '/rooms/$roomId/history',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/': typeof AuthenticatedIndexRoute
  '/ledger': typeof AuthenticatedLedgerRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/log-in/': typeof LogInIndexRoute
  '/users': typeof AuthenticatedAdminUsersRoute
  '/bookings/$bookingId': typeof AuthenticatedBookingsBookingIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/bookings/': typeof AuthenticatedBookingsIndexRoute
  '/rooms/': typeof AuthenticatedRoomsIndexRoute
  '/timeline/': typeof AuthenticatedTimelineIndexRoute
  '/rooms/$roomId/history': typeof AuthenticatedRoomsRoomIdHistoryRoute
  '/rooms/$roomId/': typeof AuthenticatedRoomsRoomIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthenticatedIndexRoute
  '/ledger': typeof AuthenticatedLedgerRoute
  '/dashboard': typeof DashboardIndexRoute
  '/log-in': typeof LogInIndexRoute
  '/users': typeof AuthenticatedAdminUsersRoute
  '/bookings/$bookingId': typeof AuthenticatedBookingsBookingIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/bookings': typeof AuthenticatedBookingsIndexRoute
  '/rooms': typeof AuthenticatedRoomsIndexRoute
  '/timeline': typeof AuthenticatedTimelineIndexRoute
  '/rooms/$roomId/history': typeof AuthenticatedRoomsRoomIdHistoryRoute
  '/rooms/$roomId': typeof AuthenticatedRoomsRoomIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_authenticated/_admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/ledger': typeof AuthenticatedLedgerRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/log-in/': typeof LogInIndexRoute
  '/_authenticated/_admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/bookings/$bookingId': typeof AuthenticatedBookingsBookingIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_authenticated/bookings/': typeof AuthenticatedBookingsIndexRoute
  '/_authenticated/rooms/': typeof AuthenticatedRoomsIndexRoute
  '/_authenticated/timeline/': typeof AuthenticatedTimelineIndexRoute
  '/_authenticated/rooms/$roomId/history': typeof AuthenticatedRoomsRoomIdHistoryRoute
  '/_authenticated/rooms/$roomId/': typeof AuthenticatedRoomsRoomIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/dashboard'
    | '/'
    | '/ledger'
    | '/dashboard/'
    | '/log-in/'
    | '/users'
    | '/bookings/$bookingId'
    | '/api/auth/$'
    | '/bookings/'
    | '/rooms/'
    | '/timeline/'
    | '/rooms/$roomId/history'
    | '/rooms/$roomId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ledger'
    | '/dashboard'
    | '/log-in'
    | '/users'
    | '/bookings/$bookingId'
    | '/api/auth/$'
    | '/bookings'
    | '/rooms'
    | '/timeline'
    | '/rooms/$roomId/history'
    | '/rooms/$roomId'
  id:
    | '__root__'
    | '/dashboard'
    | '/_authenticated'
    | '/_authenticated/_admin'
    | '/_authenticated/ledger'
    | '/_authenticated/'
    | '/dashboard/'
    | '/log-in/'
    | '/_authenticated/_admin/users'
    | '/_authenticated/bookings/$bookingId'
    | '/api/auth/$'
    | '/_authenticated/bookings/'
    | '/_authenticated/rooms/'
    | '/_authenticated/timeline/'
    | '/_authenticated/rooms/$roomId/history'
    | '/_authenticated/rooms/$roomId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LogInIndexRoute: typeof LogInIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/log-in/': {
      id: '/log-in/'
      path: '/log-in'
      fullPath: '/log-in/'
      preLoaderRoute: typeof LogInIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ledger': {
      id: '/_authenticated/ledger'
      path: '/ledger'
      fullPath: '/ledger'
      preLoaderRoute: typeof AuthenticatedLedgerRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_admin': {
      id: '/_authenticated/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/timeline/': {
      id: '/_authenticated/timeline/'
      path: '/timeline'
      fullPath: '/timeline/'
      preLoaderRoute: typeof AuthenticatedTimelineIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/rooms/': {
      id: '/_authenticated/rooms/'
      path: '/rooms'
      fullPath: '/rooms/'
      preLoaderRoute: typeof AuthenticatedRoomsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/bookings/': {
      id: '/_authenticated/bookings/'
      path: '/bookings'
      fullPath: '/bookings/'
      preLoaderRoute: typeof AuthenticatedBookingsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/bookings/$bookingId': {
      id: '/_authenticated/bookings/$bookingId'
      path: '/bookings/$bookingId'
      fullPath: '/bookings/$bookingId'
      preLoaderRoute: typeof AuthenticatedBookingsBookingIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_admin/users': {
      id: '/_authenticated/_admin/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/rooms/$roomId/': {
      id: '/_authenticated/rooms/$roomId/'
      path: '/rooms/$roomId'
      fullPath: '/rooms/$roomId/'
      preLoaderRoute: typeof AuthenticatedRoomsRoomIdIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/rooms/$roomId/history': {
      id: '/_authenticated/rooms/$roomId/history'
      path: '/rooms/$roomId/history'
      fullPath: '/rooms/$roomId/history'
      preLoaderRoute: typeof AuthenticatedRoomsRoomIdHistoryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface DashboardRouteRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedLedgerRoute: typeof AuthenticatedLedgerRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedBookingsBookingIdRoute: typeof AuthenticatedBookingsBookingIdRoute
  AuthenticatedBookingsIndexRoute: typeof AuthenticatedBookingsIndexRoute
  AuthenticatedRoomsIndexRoute: typeof AuthenticatedRoomsIndexRoute
  AuthenticatedTimelineIndexRoute: typeof AuthenticatedTimelineIndexRoute
  AuthenticatedRoomsRoomIdHistoryRoute: typeof AuthenticatedRoomsRoomIdHistoryRoute
  AuthenticatedRoomsRoomIdIndexRoute: typeof AuthenticatedRoomsRoomIdIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedLedgerRoute: AuthenticatedLedgerRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedBookingsBookingIdRoute: AuthenticatedBookingsBookingIdRoute,
  AuthenticatedBookingsIndexRoute: AuthenticatedBookingsIndexRoute,
  AuthenticatedRoomsIndexRoute: AuthenticatedRoomsIndexRoute,
  AuthenticatedTimelineIndexRoute: AuthenticatedTimelineIndexRoute,
  AuthenticatedRoomsRoomIdHistoryRoute: AuthenticatedRoomsRoomIdHistoryRoute,
  AuthenticatedRoomsRoomIdIndexRoute: AuthenticatedRoomsRoomIdIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LogInIndexRoute: LogInIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
